CREATE TABLE IF NOT EXISTS savedLists(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT,description TEXT);


CREATE TABLE IF NOT EXISTS savedItems(id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT, listId INTEGER);
